apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hajimari
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
  - rbac.yaml
  - service.yaml
